# order-postgres/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-postgres-config
  namespace: order-postgres
  labels:
    app.kubernetes.io/name: order-postgres
    app.kubernetes.io/component: config
data:
  PGDATA: "/var/lib/postgresql/data/pgdata"
  POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
